### ISSUE TITLE
Failing to precompile

### ISSUE THREAD

**Issue by Intrepidd** [jhollingworth/bootstrap-wysihtml5#180]
Hey,

I'm running the last version on rubygems and i got a problem.

In development environment everthing is working fine, although, i can't precompile the assets to push them in production

Here is what i got : 

```
/Users/Intrepidd/.rvm/rubies/ruby-1.9.3-p327-turbo/bin/ruby /Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
Unexpected token: punc ()) (line: 688, col: 10, pos: 16782)

Error
    at new JS_Parse_Error (<eval>:1720:22)
    at js_error (<eval>:1728:15)
    at croak (<eval>:2189:17)
    at token_error (<eval>:2196:17)
    at unexpected (<eval>:2202:17)
    at Object.semicolon [as 1] (<eval>:2222:51)
    at prog1 (<eval>:2770:29)
    at simple_statement (<eval>:2362:35)
    at <eval>:2270:35
    at block_ (<eval>:2459:32)
  (in /Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/bootstrap-wysihtml5-rails-0.3.1.13/vendor/assets/javascripts/bootstrap-wysihtml5/locales/index.js)
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:34:in `rescue in block in eval'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:28:in `block in eval'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:80:in `block in lock'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:78:in `call'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:78:in `Locker'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:78:in `lock'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:27:in `eval'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/execjs-1.4.0/lib/execjs/ruby_racer_runtime.rb:19:in `exec'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/uglifier-1.3.0/lib/uglifier.rb:100:in `compile'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/compressors.rb:74:in `compress'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/processing.rb:265:in `block in js_compressor='
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/processor.rb:29:in `call'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/processor.rb:29:in `evaluate'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/bundled_asset.rb:26:in `initialize'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `new'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `build_asset'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/static_compiler.rb:19:in `block in compile'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/static_compiler.rb:18:in `compile'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/assets.rake:56:in `internal_precompile'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:primary
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/Users/Intrepidd/.rvm/rubies/ruby-1.9.3-p3...]
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/Users/Intrepidd/.rvm/gems/ruby-1.9.3-p327-turbo/gems/actionpack-3.2.9/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

Any idea ?

**Comment by Intrepidd** [comment]
Sory i posted on this repository, i should have posted on the repository of the gem, closing.
